#!/usr/sbin/nft -f

flush ruleset
table ip pi_router {
	chain forward {
		type filter hook forward priority filter; policy drop;
		iifname "eth1" oifname "eth0" ct state { established, related, new } counter packets 2072 bytes 1269077 accept
		iifname "eth0" oifname "eth1" ct state { established, related } counter packets 2755 bytes 1422675 accept
	}

	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;
		oifname "eth0" ip saddr 192.168.50.0/24 counter packets 112 bytes 61156 masquerade
	}
}
